// <auto-generated />
using System;
using API_Colecoes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace API_Colecoes.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20190514122716_ModeloTabelas")]
    partial class ModeloTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("API_Colecoes.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor")
                        .IsRequired();

                    b.Property<string>("Bairro");

                    b.Property<string>("Categoria")
                        .IsRequired();

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<string>("Contato_emprestado");

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Estado");

                    b.Property<string>("ImgPath")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Nome_emprestado");

                    b.Property<int?>("Numero");

                    b.Property<string>("Rua");

                    b.Property<string>("Tipo")
                        .IsRequired();

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
