<div class="dropdown mt-3">
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="botaoMenu" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Ordem</button>
                        <div class="dropdown-menu" aria-labelledby="botaoMenu">
                            <a href="#" class="dropdown-item">Crescente</a>
                            <a href="#" class="dropdown-item">Decrescente</a>
                        </div>
                    </div>